In [1]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
np.random.seed(0)

In [6]:
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [14]:
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)

In [86]:
df['target']=iris.target

In [89]:
df.target.unique()

array([0, 1, 2])

In [90]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  target  
0  setosa      True       0  
1  setosa     False       0  
2  setosa      True       0  
3  setosa      True       0  
4  setosa      True       0

In [93]:
X=df.drop(['species','target','is_train'],axis='columns')

In [94]:
y=df.target

In [95]:
print(f'The shape of X{X.shape}')
print(f'The shape of y{y.shape}')

The shape of X(150, 4)
The shape of y(150,)


In [96]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [97]:
import pandas as pd
from sklearn.model_selection import GridSearchCV, ShuffleSplit
from sklearn.linear_model import Lasso, LinearRegression
from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchcv(X, y):
    algos = {
        'linear_regression': {
            'model': LinearRegression(),
            'params': {}  
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1, 2],
                'selection': ['random', 'cyclic']
            }
        },
        'decision_tree': {
            'model': DecisionTreeRegressor(),
            'params': {
                'criterion': ['squared_error', 'friedman_mse'], 
                'splitter': ['best', 'random']
            }
        }
    }
    
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

    for algo_name, config in algos.items():
        gs = GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(X, y)
        
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])

# Call function
find_best_model_using_gridsearchcv(X, y)

model  best_score  \
0  linear_regression    0.924815   
1              lasso    0.386107   
2      decision_tree    0.938185   

                                         best_params  
0                                                 {}  
1                {'alpha': 1, 'selection': 'random'}  
2  {'criterion': 'squared_error', 'splitter': 'be...

In [98]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()

In [99]:
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [101]:
y_pred=clf.predict(X_test)

In [102]:
from sklearn import metrics
accuracy=metrics.accuracy_score(y_pred,y_test)

In [103]:

print(f'Accuracy score{accuracy}')

Accuracy score1.0


In [104]:
clf.predict([[4.6,3.1,1.5,0.2]])

C:\Users\XXXX\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [106]:
 clf.predict([[7.0,3.2,4.7,1.4]])

C:\Users\XXXX\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])